### ISSUE TITLE
java.lang.NullPointerException in Version 5.3.0

### ISSUE THREAD

**Issue by MAndretti** [mikepenz/AboutLibraries#171]
Hi Mike,

thanks for #170, but ...

```
java.lang.RuntimeException: An error occured while executing doInBackground()
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean com.mikepenz.aboutlibraries.LibsBuilder.aboutShowIcon' on a null object reference
at com.mikepenz.aboutlibraries.LibsFragmentCompat$LibraryTask.doInBackground(LibsFragmentCompat.java:91)
at com.mikepenz.aboutlibraries.LibsFragmentCompat$LibraryTask.doInBackground(LibsFragmentCompat.java:64)
```

my code:
```java
return new LibsBuilder()
		.withAboutIconShown(true)
                .withAnimations(false)
                .withExcludedLibraries("NineOldAndroids", "gson")
		.withAboutVersionShown(true)
		.withAboutDescription("some text")
                .fragment();
```

Something wrong?

Regards,
Mario

**Comment by mikepenz** [comment]
@MAndretti i can check in 10hours. Seems weird. Tested the `.supportFragment()` which is an exact copy just with the different fragment type and this works :/

**Comment by mikepenz** [comment]
just tried it:

```java

        LibsFragment fragment = new LibsBuilder()
                .withAboutIconShown(true)
                .withAnimations(false)
                .withExcludedLibraries("NineOldAndroids", "gson")
                .withAboutVersionShown(true)
                .withAboutDescription("some text")
                .fragment();

        FragmentManager fragmentManager = getFragmentManager();
        fragmentManager.beginTransaction().replace(R.id.frame_container, fragment).commit();
```

does not crash for me

**Comment by MAndretti** [comment]
@mikepenz 
i use Linux, Android Studio 1.5 and your current lib. Error. (Google image and genymotion - different API Level).
If i use Windows Android Studio 1.4 and your cuurent lib, works fine (Google image - defferent API Level).

if i use Linux, Android Studio 1.5 and your lib (old version). works fine. (Google image and genymotion - different API Level).

If i copy the latest source into my project, i get no error. But the Fragment is empty.

I am very confused.

All i need is a Fragment, with transition an no scatter ...

Regards,
Mario

**Comment by mikepenz** [comment]
@MAndretti no log output? can you debug?

**Comment by MAndretti** [comment]
@mikepenz 

the crash log, ...

java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean com.mikepenz.aboutlibraries.LibsBuilder.aboutShowIcon' on a null object reference
                                                                         at com.mikepenz.aboutlibraries.LibsFragmentCompat$LibraryTask.doInBackground(LibsFragmentCompat.java:91)
                                                                         at com.mikepenz.aboutlibraries.LibsFragmentCompat$LibraryTask.doInBackground(LibsFragmentCompat.java:64)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                         at java.lang.Thread.run(Thread.java:818)

**Comment by mikepenz** [comment]
@MAndretti i can add a `null` check. But i do not know why this field is null. 

What's the device / emulator. And which Android version?

**Comment by MAndretti** [comment]
@mikepenz

devices: Nexus 4, Nexus 5, Nexus 5x, Nexus 6, Nexus 7
emulator: Google and Genymotion
Android version: 5.0, 5.1, 5.1.1 and 6.0.0
Chipset: Intel
OS: Linux (not OK)
OS: Windows (OK)

The best result was an empty Fragment/View ...

**Comment by MAndretti** [comment]
@mikepenz 

The old version (< #170) works fine ... Always ...

Regards,
Mario

**Comment by mikepenz** [comment]
@MAndretti the old version also does **not** use the `AsynchTask` to load the libs after the view was created. this will cause some lag

**Comment by mikepenz** [comment]
@MAndretti i have changed some things. Could you please try to run the new source?

**Comment by MAndretti** [comment]
@mikepenz

test on Android 5.0, 5.1 and 6.0 (Google-Image and Genymotion) looks good. No error :)

The animation could be a bit smoother (at first call).

**Comment by mikepenz** [comment]
@MAndretti with the latest source. The animation is a normal `DefaultItemAnimator` and the list is shown after the data is loaded. No more optimization possible here.

**Comment by mikepenz** [comment]
will release a new version with the fixes later today
