### ISSUE TITLE
Crash using appcompat 23.2.0 with LIGHT_DARK_TOOLBAR

### ISSUE THREAD

**Issue by Oyashirox** [mikepenz/AboutLibraries#191]
Hi, and thank you for your lib !
By updating my dependencies to appcompat 23.2.0 like this :
```
    compile 'com.android.support:appcompat-v7:23.2.0'
    compile 'com.android.support:design:23.2.0'
```
The app crash when I try to start an activity with LIGHT_DARK_TOOLBAR style.
Here is the stacktrace :

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.NoSuchFieldError: com.mikepenz.aboutlibraries.R$drawable.abc_ic_ab_back_mtrl_am_alpha
                                                       at com.mikepenz.aboutlibraries.ui.LibsActivity.onCreate(LibsActivity.java:74)
                                                       at android.app.Activity.performCreate(Activity.java:5226)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
                                                       at com.lbe.security.service.core.client.b.x.callActivityOnCreate(Unknown Source)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2310)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2398)
                                                       at android.app.ActivityThread.access$600(ActivityThread.java:162)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:153)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5356)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                       at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mikepenz** [comment]
@Oyashirox I have planned to update all my libs later today.
You might want to exclude the support libs from my libs for the moment

**Comment by mikepenz** [comment]
@Oyashirox fixed in latest version
