### ISSUE TITLE
NoSuchFieldError after updating to com.android.tools.build:gradle:2.0.0-beta6 and latest AppCompat

### ISSUE THREAD

**Issue by Montanax** [mikepenz/AboutLibraries#193]
About libraries version: 5.5.7

Stacktrace:

```
java.lang.NoSuchFieldError: No static field abc_ic_ab_back_mtrl_am_alpha of type I in class Lcom/mikepenz/aboutlibraries/R$drawable; or its superclasses (declaration of 'com.mikepenz.aboutlibraries.R$drawable' appears in /data/data/.../files/instant-run/dex/slice-slice_2_ada40d925341ae4238319f285ef8a5db7bf8ad7b-classes.dex)
                                                                                  at com.mikepenz.aboutlibraries.ui.LibsActivity.onCreate(LibsActivity.java:74)
                                                                                  at android.app.Activity.performCreate(Activity.java:6251)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by mikepenz** [comment]
are you sure you used v5.5.7? because this was solved with v5.5.7

**Comment by Montanax** [comment]
Apparently Android studio was bugging out or something because it works again after a full clean.

**Comment by amit47billion** [comment]
you are using lesser version of support library so please update support library to 'com.android.support:design:23.2.0' or higher , this error will automatically get resolved
