### ISSUE TITLE
Proguard `IllegalArgumentException` at `valueOf()`

### ISSUE THREAD

**Issue by jaredsburrows** [mikepenz/AboutLibraries#208]
**Caused by: java.lang.IllegalArgumentException: Default is not a constant in com.mikepenz.aboutlibraries.d at java.lang.Enum.valueOf(Enum.java:192) at**

Full stacktrace:
```
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{<>/com.mikepenz.aboutlibraries.ui.LibsActivity}: java.lang.IllegalArgumentException: 
Default is not a constant in com.mikepenz.aboutlibraries.d at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074) at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2099) at 
android.app.ActivityThread.access$600(ActivityThread.java:145) at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210) at 
android.os.Handler.dispatchMessage(Handler.java:119) at android.os.Looper.loop(Looper.java:137) at 
android.app.ActivityThread.main(ActivityThread.java:4873) at 
java.lang.reflect.Method.invokeNative(Native Method) at 
java.lang.reflect.Method.invoke(Method.java:528) at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) at dalvik.system.NativeStart.main(Native 
Method) Caused by: java.lang.IllegalArgumentException: Default is not a constant in 
com.mikepenz.aboutlibraries.d at java.lang.Enum.valueOf(Enum.java:192) at 
com.mikepenz.aboutlibraries.d.valueOf(SourceFile:38) at 
com.mikepenz.aboutlibraries.ui.LibsActivity.onCreate(SourceFile:38) at 
android.app.Activity.performCreate(Activity.java:5218) at 
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2038) ... 11 more
```

Do you think proguard is causing this?

**Comment by mikepenz** [comment]
@jaredsburrows is it running in debug? (wihtout proguard?

**Comment by jaredsburrows** [comment]
@mikepenz This is an error I got from the Play Store. All my apps are proguarded, I can not reproduce this issue. I'll try adding in those extra lines to my proguard file.

**Comment by mikepenz** [comment]
@jaredsburrows oh weird. perhaps a device or modified android os specific issue somewhere. Hard to tell.
