### ISSUE TITLE
Bug: java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by Z3r0byte** [mikepenz/AboutLibraries#249]
When I start a new Library-activity, it crashes with the following stack trace:

`java.lang.AbstractMethodError: abstract method "boolean com.mikepenz.fastadapter.IExpandable.isAutoExpanding()"
 at com.mikepenz.fastadapter.FastAdapter$1.onClick(FastAdapter.java:406)
 at android.view.View.performClick(View.java:5204)
 at android.view.View$PerformClick.run(View.java:21158)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:5461)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)`

My code:
`new LibsBuilder()
          .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
          .start(activity.getApplicationContext());`

I already tried a clean gradle build and restarting Android Studio.

**Comment by Z3r0byte** [comment]
Oops, seems to be an issue with your NavigationDrawer Library. However it started when I added this library.

**Comment by Z3r0byte** [comment]
Fixed by updating the drawer library to the newest version.

**Comment by mikepenz** [comment]
@Z3r0byte I removed some methods with the latest release as I stopped supporting minSdk 10. New minSdk is 14. As the `MaterialDrawer` is based on the `FastAdapter` it requires both to play with each other. ;)

**Comment by Z3r0byte** [comment]
Oh, I see. :)
