### ISSUE TITLE
Crash when starting AboutLibraries Activity

### ISSUE THREAD

**Issue by IonutNegru87** [mikepenz/AboutLibraries#279]
Hello,

I encountered an crash when I'm trying to start the activity. 

This is the builder I've used:
 ```
new LibsBuilder()
    .withFields(R.string.class.getFields())
    .withLicenseShown(true)
    .withVersionShown(true)
    .withAboutIconShown(true)
    .withAboutDescription(getString(R.string.app_description))
    .withActivityTitle(getString(R.string.title_activity_about))
    .withActivityTheme(R.style.AppTheme)
    .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
    .start(getContext());
```
These are the logs generated:
```
12-15 12:55:55.294 8283-8283/com.ionut.negru.flashpower E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.ionut.negru.flashpower, PID: 8283
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ionut.negru.flashpower/com.mikepenz.aboutlibraries.ui.LibsActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
  at android.app.ActivityThread.access$800(ActivityThread.java:151)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5349)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
  at android.support.v7.app.AppCompatDelegateImplV9.setSupportActionBar(AppCompatDelegateImplV9.java:199)
  at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:133)
  at com.mikepenz.aboutlibraries.ui.LibsActivity.onCreate(LibsActivity.java:68)
  at android.app.Activity.performCreate(Activity.java:6020)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2284)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391) 
  at android.app.ActivityThread.access$800(ActivityThread.java:151) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309) 
  at android.os.Handler.dispatchMessage(Handler.java:102) 
  at android.os.Looper.loop(Looper.java:135) 
  at android.app.ActivityThread.main(ActivityThread.java:5349) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at java.lang.reflect.Method.invoke(Method.java:372) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) 
```

The theme is simple:

    <style name="AppTheme" parent="Theme.AppCompat">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="colorControlHighlight">@color/colorControlHighlight</item>
    </style>
```

**Comment by mikepenz** [comment]
@IonutNegru87 please use a theme without the `ActionBar` so either you define that it has no actionbar or you use the `Theme.AppCompat.NoActionBar` theme for the aboutLibs activity

**Comment by IonutNegru87** [comment]
Hello @mikepenz,
This is what I did to solve this issue, but I think this can be detected by the library in order to avoid crashes like this. Until then, I think an update of the documentation can be done so that others know how to avoid this.

Thank you for the great library and for your time.

**Comment by friederbluemle** [comment]
Depending on the size and number of components of an app, requiring a global override/change of the app theme may be a bit risky.. 

I was able to fix this exception by just adding this to `AndroidManifest.xml`:

```xml
        <activity
            android:name="com.mikepenz.aboutlibraries.ui.LibsActivity"
            android:theme="@style/Theme.MaterialComponents.NoActionBar" />
```

**Comment by daberni** [comment]
Imho it should be stated somewhere in the Readme, that a `NoActionBar` theme is necessary and has to be configured like @friederbluemle did

**Comment by mikepenz** [comment]
@daberni I always appreciate if people contribute to enhance documentation. 

I actually am surprised that people still use `ActionBar`s, those things are super old :D.

**Comment by daberni** [comment]
I guess I will find some time the next days ;)

Yeah, just like the app we are maintaining is super old :D

**Comment by daberni** [comment]
Any reason why you dropped `.withActivityTheme(...)`?

**Comment by mikepenz** [comment]
In favor of offering a lot more flexibility by defining theme based styles which will then accordingly apply to the UI: https://github.com/mikepenz/AboutLibraries#style-the-aboutlibraries-%EF%B8%8F

The activity offered around the `AboutLibraries` UI is actually only a super thin wrapper. 
The UI itself is the fragment which you could directly commit in the app and then we can't really have the parent theme any different. 

Additionally it is more accurate to define it via XML in the manifest if needed :)
