### ISSUE TITLE
Crash when using LibraryComparator

### ISSUE THREAD

**Issue by Scrounger** [mikepenz/AboutLibraries#284]
@mikepenz:
App crash on click (open url) if using the LibraryComparator like in your Example [CustomSortActivity.java
](https://github.com/mikepenz/AboutLibraries/blob/develop/app/src/main/java/com/mikepenz/aboutlibraries/sample/CustomSortActivity.java)

```
public class OpenSourceLicenseActivity extends LibsActivity {
    private final static String logTAG = OpenSourceLicenseActivity.class.getName() + ".";

    @Override
    public void onCreate(Bundle savedInstanceState) {

        LibsBuilder builder = new LibsBuilder()
                .withFields(R.string.class.getFields())
                .withActivityTheme(R.style.OpenSourceLicenseActivity)
                .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
                .withAutoDetect(true)
                .withLicenseShown(true)
                .withLicenseDialog(true)
                .withVersionShown(true)
                .withActivityTitle(getString(R.string.open_source_licenses))
                .withLibraryComparator(new LibraryComparator());


//        logExternalLibs();

        setIntent(builder.intent(this));

        super.onCreate(savedInstanceState);
    }


    private void logExternalLibs() {
        Libs libs = new Libs(this);
        ArrayList<Library> externLibraries = libs.prepareLibraries(this, GenericsUtil.getFields(this), null, true, true);
        for (Library lib : externLibraries) {
            Log.d(logTAG + "logExternalLibs", lib.getDefinedName());
        }
    }

    private class LibraryComparator implements Comparator<Library>, Serializable {
        // Nach Name aufsteigend sortieren
        @Override
        public int compare(Library lhs, Library rhs) {
            // Just to show you can sort however you might want to...
            int result = lhs.getAuthor().compareTo(rhs.getAuthor());
            if (result == 0) {
                // Backwards sort by lib name.
                result = rhs.getLibraryName().compareTo(lhs.getLibraryName());
            }
            return result;
        }
    }
}
```

Error message:
```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.mikepenz.aboutlibraries.LibsBuilder)
                                                             at android.os.Parcel.writeSerializable(Parcel.java:1447)
                                                             at android.os.Parcel.writeValue(Parcel.java:1395)
                                                             at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
                                                             at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
                                                             at android.os.Bundle.writeToParcel(Bundle.java:1079)
                                                             at android.os.Parcel.writeBundle(Parcel.java:690)
                                                             at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:148)
                                                             at android.os.Parcel.writeTypedArray(Parcel.java:1233)
                                                             at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:563)
                                                             at android.os.Parcel.writeParcelable(Parcel.java:1416)
                                                             at android.os.Parcel.writeValue(Parcel.java:1322)
                                                             at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
                                                             at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
                                                             at android.os.Bundle.writeToParcel(Bundle.java:1079)
                                                             at android.os.Parcel.writeBundle(Parcel.java:690)
                                                             at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3152)
                                                             at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3417)
                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at android.os.Looper.loop(Looper.java:148)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                          Caused by: java.io.NotSerializableException: .Activties.OpenSourceLicenseActivity
                                                             at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
                                                             at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                             at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                             at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                             at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                             at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                             at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                             at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                             at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                             at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                             at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                             at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                             at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                             at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                             at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                             at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                             at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                             at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                             at android.os.Parcel.writeSerializable(Parcel.java:1442)
                                                             at android.os.Parcel.writeValue(Parcel.java:1395) 
                                                             at android.os.Parcel.writeArrayMapInternal(Parcel.java:665) 
                                                             at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330) 
                                                             at android.os.Bundle.writeToParcel(Bundle.java:1079) 
                                                             at android.os.Parcel.writeBundle(Parcel.java:690) 
                                                             at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:148) 
                                                             at android.os.Parcel.writeTypedArray(Parcel.java:1233) 
                                                             at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:563) 
                                                             at android.os.Parcel.writeParcelable(Parcel.java:1416) 
                                                             at android.os.Parcel.writeValue(Parcel.java:1322) 
                                                             at android.os.Parcel.writeArrayMapInternal(Parcel.java:665) 
                                                             at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330) 
                                                             at android.os.Bundle.writeToParcel(Bundle.java:1079) 
                                                             at android.os.Parcel.writeBundle(Parcel.java:690) 
                                                             at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3152) 
                                                             at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3417) 
                                                             at android.os.Handler.handleCallback(Handler.java:739) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                             at android.os.Looper.loop(Looper.java:148) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Without using the LibraryComparator all works fine.

**Comment by mikepenz** [comment]
@Scrounger something is related to your code as it crashes with your activity
```
Caused by: java.io.NotSerializableException: .Activties.OpenSourceLicenseActivity
```

**Comment by rfc2822** [comment]
Have experienced this, too.

When using this fragment:

    1 -> LibsBuilder()
            .withAutoDetect(false)
            .withLicenseShown(true)
            .withLibraryComparator { o1, o2 ->
                val vip1 = vipLibraries.contains(o1.definedName)
                val vip2 = vipLibraries.contains(o2.definedName)
                if (vip1 == vip2)
                    o1.libraryName.compareTo(o2.libraryDescription)
                else
                    vip2.compareTo(vip1)
            }
            .supportFragment()

the activity crashes at soon as it is resumed. This is because the comparator can't be serialized. It does not happen when there's no comparator

Steps to reproduce:

1. Create an `AppCompatActivity` and embed a fragment created by `LibsBuilder.withLibraryComparator().supportFragment()`.
2. Start this activity.
3. Move away from the activity (e.g. switch to another app)
4. Switch back to the activity.

Result: activity crashes with `NotSerializableException`.

Expected result: activity should not crash.

Maybe the comparator cannot be used with the AboutLibraries fragment? In this case, I suggest to throw an `IllegalArgumentException` in `supportFragment()` when a library comparator is set.
