### ISSUE TITLE
Colored NavBar

### ISSUE THREAD

**Issue by NajeraP95** [mikepenz/AboutLibraries#287]
Hello, 
I tried to put a colored nav bar in the About Libraries Activity. First I put:

```
.withActivityTheme(R.style.AppTheme)
``` 

and it has error:

```
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime: Process: com.example.jorgenajera.myapplication, PID: 7068
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.jorgenajera.myapplication/com.mikepenz.aboutlibraries.ui.LibsActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5461)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:  Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV9.setSupportActionBar(AppCompatDelegateImplV9.java:203)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:133)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at com.mikepenz.aboutlibraries.ui.LibsActivity.onCreate(LibsActivity.java:68)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6251)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148) 
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5461) 
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
01-24 14:11:16.487 7068-7068/com.example.jorgenajera.myapplication E/AndroidRuntime:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) 
```

so i tried with: 

```
.withActivityTheme(R.style.AppTheme_NoActionBar)
```

and its works but now the Back Button and the AppTitle is black 

I tried with:

```
.withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
.withActivityStyle(Libs.ActivityStyle.LIGHT)
.withActivityStyle(Libs.ActivityStyle.DARK)
```

LIGHT_DARK_TOOLBAR: Black Back Button
DARK: Both Dark
LIGHT: Both Dark

But it doesn´t work

![screenshot_20170124-135511](https://cloud.githubusercontent.com/assets/9758564/22264574/16203d7e-e23e-11e6-9b57-da1cc900ca25.png)

**Comment by mikepenz** [comment]
@NajeraP95 this works in the sample app with the following code:
https://github.com/mikepenz/AboutLibraries/blob/develop/app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.java#L69

Just try it out
