### ISSUE TITLE
NullPointerException on activity's onStart

### ISSUE THREAD

**Issue by guntherhoppe** [mikepenz/AboutLibraries#306]
I observe a sporadic NullPointerException on Android 7.1.1 (devices: Nexus 5X, Nexus 6P, Pixel XL, Pixel) when an activity is restarted after it has been moved to background since a while.
I use AboutLibraries version 5.6.8.

Stack trace:
```
02-18 12:13:48.917 E/ACRA    (12457): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
02-18 12:13:48.917 E/ACRA    (12457): 	at com.mikepenz.aboutlibraries.ui.LibsSupportFragment.onCreateView(LibsSupportFragment.java:26)
02-18 12:13:48.917 E/ACRA    (12457): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
02-18 12:13:48.917 E/ACRA    (12457): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
02-18 12:13:48.917 E/ACRA    (12457): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
02-18 12:13:48.917 E/ACRA    (12457): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1268)
02-18 12:13:48.917 E/ACRA    (12457): 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2143)
02-18 12:13:48.917 E/ACRA    (12457): 	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
02-18 12:13:48.917 E/ACRA    (12457): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:615)
02-18 12:13:48.917 E/ACRA    (12457): 	at ch.srf.android.core.activity.Activity.onStart(Activity.java:748)
02-18 12:13:48.917 E/ACRA    (12457): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
02-18 12:13:48.917 E/ACRA    (12457): 	at android.app.Activity.performStart(Activity.java:6696)
02-18 12:13:48.917 E/ACRA    (12457): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
02-18 12:13:48.917 E/ACRA    (12457): 	... 9 more
```

**Comment by mikepenz** [comment]
@guntherhoppe please update to the latest version and try again

**Comment by guntherhoppe** [comment]
@mikepenz: I use a lesser version of the support libs in my app, which results in build errors when I update AboutLibraries to the latest version.

**Comment by mikepenz** [comment]
@guntherhoppe gradle allows you to exclude dependencies of libs
http://stackoverflow.com/a/36103326/325479

**Comment by guntherhoppe** [comment]
@mikepenz: Mhh - I will try. Thanks. 
But I'm wondering why you are closing this issue now (and uncommented)? Will the latest version fix this problem for sure, or (means is it a known issue)? It did not sound like that ...
