### ISSUE TITLE
Using AboutLibraries 6.0.0 with MaterialDrawer is causing build failures

### ISSUE THREAD

**Issue by aminecmi** [mikepenz/AboutLibraries#350]
Hello (not really sure if I had to report the issue on this lib or MaterialDrawer),

I have AboutLibraries v5.9.7 and MaterialDrawer v5.9.5 on my app (working great).

I wanted to update AboutLibraries to the last version, but it was causing a build issue when assembling the app.
```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.mikepenz.materialdrawer.model.interfaces.IDrawerItem, unresolved supertypes: com.mikepenz.fastadapter.IExpandable, com.mikepenz.fastadapter.ISubItem
```

I tried updating the MaterialDrawer lib to v6.0.0 and v6.0.1, but it's still failing with a different issue:

```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/mikepenz/materialdrawer/AccountHeaderBuilder;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/mikepenz/materialdrawer/AccountHeaderBuilder;
    
com.android.dex.DexException: Multiple dex files define Lcom/mikepenz/materialdrawer/AccountHeaderBuilder;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I also tried using the [kotlin wrapper](https://github.com/zsmb13/MaterialDrawerKt). But it's also failing [as you can see on the issue there](https://github.com/zsmb13/MaterialDrawerKt/issues/61).

Is there a fix for this ?

Thanks!

**Comment by mikepenz** [comment]
@aminecmi only AboutLibs 6.x is compatible with MaterialDrawer 6.x. 

In addition you have to use the latest support libraries 27, and support libs 27 will need compile and target 27

**Comment by mikepenz** [comment]
The error you show basically says that you have 2 MaterialDrawer libraries with different versions in your dependencies

```gradle
./gradlew dependencies
```

should show you where

**Comment by aminecmi** [comment]
@mikepenz I couldn't have two MaterialDrawer libraries at the same time, because I was updating the line of the older version.

Updating to support libraries 27 seamed to resolve the issue. Shouldn't it be added in the migration guide ?

**Comment by mikepenz** [comment]
It is written in the changelog. Also the libs always try to stay on top of the support libs :)

But you can also just overwrite the used version with what you need:
https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L86

**Comment by aminecmi** [comment]
It is said in the changelog, but I didn't know that I HAD to update my app too.

Thanks for the help.

**Comment by mikepenz** [comment]
that's a general thing of the support libraries. They have to match. 

as the linked thing. you can always just define which version to use
