### ISSUE TITLE
java.lang.NoClassDefFoundError with V26

### ISSUE THREAD

**Issue by DaveMG3** [mikepenz/AboutLibraries#351]
Hi,
This issue might have already been raised but I cant find any references in search.
I guess the culprit is going to V26 and I follow the migration guide

`java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                                                                            at com.mikepenz.itemanimators.BaseItemAnimator.resetAnimation(BaseItemAnimator.java:626)
                                                                            at com.mikepenz.itemanimators.BaseItemAnimator.animateAdd(BaseItemAnimator.java:267)
                                                                            at android.support.v7.widget.SimpleItemAnimator.animateAppearance(SimpleItemAnimator.java:128)
                                                                            at android.support.v7.widget.RecyclerView.animateAppearance(RecyclerView.java:3922)
                                                                            at android.support.v7.widget.RecyclerView$4.processAppeared(RecyclerView.java:528)
                                                                            at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:245)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3763)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3421)
                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                                                            at android.view.View.layout(View.java:16681)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5499)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                            at android.view.View.layout(View.java:16681)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5499)
                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                            at android.view.View.layout(View.java:16681)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5499)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                            at android.view.View.layout(View.java:16681)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5499)
                                                                            at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
                                                                            at android.view.View.layout(View.java:16681)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5499)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                            at android.view.View.layout(View.java:16681)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5499)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                            at android.view.View.layout(View.java:16681)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5499)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                            at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2706)
                                                                            at android.view.View.layout(View.java:16681)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5499)
                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2305)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2035)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1211)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6532)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5515)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654)
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorCompatHelper" on path: DexPathList[[zip file "/data/app/com.example.staffbeta1-1/base.apk", zip file "/data/app/com.example.staffbeta1-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.staffbeta1-1/split_lib_slice_0_apk.apk", zip file
`

**Comment by mikepenz** [comment]
@DaveMG3 you have to use the support libraries 27 with the `AboutLibraries` v6.x

In addition make sure the used `ItemAnimator` version is also up to date with the support libraries 27

**Comment by DaveMG3** [comment]
Ah ok... previously I was on 5.9.1 with V26 libraries and thus this issue.I upgraded to your latest release to check if error was gone, it means indeed to 6.0.0 which conduct also to same issue.
Is there a version  of AboutLibrary I can use with V26?tks

**Comment by mikepenz** [comment]
You can use a resolution strategy to overwrite the version with whatever you like (as long as the API's I use are not different) 

https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L85
