### ISSUE TITLE
Crash on older Androids while starting LibsActivity with LibsBuilder (missing FLAG_ACTIVITY_NEW_TASK)

### ISSUE THREAD

**Issue by juanitobananas** [mikepenz/AboutLibraries#383]
## About this issue

The app crashes while trying to start the activity on older Android devices. It does *not* happen on Android 7.1 and onwards but definitely does on Android 5. What happens in between, I cannot tell.

Here is the code I use to run it:
```java
new LibsBuilder()
    .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
    .withAboutIconShown(true)
    .withAboutVersionShown(true)
    .withActivityTitle(getString(R.string.licenses_title))
    .withAboutDescription(getString(R.string.licenses_about_libraries_text))
    .start(getApplicationContext());
```
And this is the logcat from the crash:
```
E/AndroidRuntime( 2494): FATAL EXCEPTION: main
E/AndroidRuntime( 2494): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/AndroidRuntime( 2494): 	at android.app.ContextImpl.startActivity(ContextImpl.java:942)
E/AndroidRuntime( 2494): 	at android.app.ContextImpl.startActivity(ContextImpl.java:936)
E/AndroidRuntime( 2494): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:276)
E/AndroidRuntime( 2494): 	at com.mikepenz.aboutlibraries.LibsBuilder.start(LibsBuilder.java:583)
```
## Details
- Used library version: 6.0.8 (and 6.0.6)
- Used support library version: v7:27.1.0
- Used gradle build tools version: com.android.tools.build:gradle:3.0.1
- Used tooling / Android Studio version: Android Studio 3.1
Build #AI-173.4670197, built on March 22, 2018
JRE: 1.8.0_152-release-1024-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.9.0-6-amd64

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

## Possible fix

I have actually had exactly the same problem with a library of mine: Actually adding the flag like the log says seems to solve the problem:

```java
if (android.os.Build.VERSION.SDK_INT < Build.VERSION_CODES.N_MR1) {
    intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
}
context.startActivity(intent);
```
I didn't want to add it for most modern versions, as I know it does work there, but I am just not sure for some of the older ones.

## Thanks

Thank you very much for this cool library! :+1:

**Comment by juanitobananas** [comment]
Actually, I just realised that the most modern Android versions add the flag themselves:

```
04-13 07:58:26.547  1295  2002 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=org.example.app/com.mikepenz.aboutlibraries.ui.LibsActivity (has extras) }
```

So another option would be to just always add it instead of using the if I proposed in my previous comment.
