### ISSUE TITLE
Crash during pre-launch report on license description click

### ISSUE THREAD

**Issue by pawegio** [mikepenz/AboutLibraries#412]
## About this issue

I've just received latest Google Play pre-launch report resulting with crash on license description click. I was unable to reproduce it on my test devices. Any thoughts?

```kotlin
Fatal Exception: java.lang.IllegalArgumentException: Real screen element corresponding to shadow element ElementDescription{className=android.support.v7.widget.AppCompatTextView, resourceName=com.polaroidoriginals.po1.alpha:id/libraryDescription, contentDescription=, componentType=TEXT_VIEW, inputType=NONE, isWebViewElement=false} not found.
       at com.google.android.apps.mtaas.crawler.obfuscated.ai.x.a(PatternCompiler.java:22)
       at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.transformAction(RemotePlatform.java:76)
       at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.handlePerformActionMessage(RemotePlatform.java:21)
       at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.access$300(RemotePlatform.java:88)
       at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform$ControllerMessageHandler.handleMessage(RemotePlatform.java:8)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

The way I use `LibsBuilder`:

```kotlin
LibsBuilder()
    .withFields(R.string::class.java.fields)
    .withActivityTitle(getString(R.string.info_software_credits))
    .withActivityColor(Colors(barColor, barColor))
    .withLicenseShown(true)
    .withVersionShown(true)
    .start(context)
// invoked in Fragment
```

## Affected devices:
1. Moto G4 Play (6.0.1)
2. Pixel 2 (9.0)

## Details
- Used library version: 6.1.1
- Used support library version: 27.1.1
- Used gradle build tools version: 3.1.4

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@pawegio seems to me like the generic check in the play pre-launch report has some sort of bug, trying to click something in the recyclerview which is not where it expects it :D
