### ISSUE TITLE
UninitializedPropertyAccessException on LibsFragmentCompat

### ISSUE THREAD

**Issue by Nekromancer** [mikepenz/AboutLibraries#497]
## About this issue

- I have this crash from Crashlytics, only on Nexus 5X device. I don't have this physical device to try and reproduce the problem.
- I'm not sure how this can be reproduced, i have no logs what user did to come to this state

## Details
- Library version: 8.1.2
- Newest stable: androidx.fragment:fragment-ktx:1.2.4 androidx.core:core-ktx:1.2.0 androidx.appcompat:appcompat:1.1.0
- Gradle 6.4.1
- Android Studio 3.6.3

I'm using gradle plugin to generate library list. Then i start activity like this
```kotlin
LibsBuilder()
                .withActivityTitle("External libraries")
                .withAboutIconShown(false)
                .withVersionShown(true)
                .withSortEnabled(true)
                .withLicenseShown(true)
                .start(requireActivity())
```

On this particular device the stack track is:

```
Caused by kotlin.UninitializedPropertyAccessException: lateinit property builder has not been initialized
       at com.mikepenz.aboutlibraries.LibsFragmentCompat.executeLibTask(LibsFragmentCompat.java:101)
       at com.mikepenz.aboutlibraries.LibsFragmentCompat.onViewCreated(LibsFragmentCompat.java:95)
       at com.mikepenz.aboutlibraries.ui.LibsSupportFragment.onViewCreated(LibsSupportFragment.java:24)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
       at android.app.Activity.performStart(Activity.java:7029)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by mikepenz** [comment]
Hmmm seems it creates the view without the arguments on that phone :O 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsFragmentCompat.kt#L51-L52

and then we don't verify here if the builder got initialized:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsFragmentCompat.kt#L101

We can account for that, but then it still would be empty for that user I suppose

**Comment by Nekromancer** [comment]
Yea, i probably have to get this device just to check what the heck is going on there :)

**Comment by mikepenz** [comment]
what version of android is it running? perhaps it's somehow related to this?

**Comment by Nekromancer** [comment]
8.1.0

**Comment by mikepenz** [comment]
Hmmm very strange. anyways I will push an update with the late init protection. 
I also tried the "Don't keep activities" which was my only guess, but wouldn't crash on me either :/

**Comment by mikepenz** [comment]
v8.1.3 has the initialized check so it won't crash but yeah :/

**Comment by mikepenz** [comment]
I hope 8.1.3 could help? if you have any more information I'd really appreciate it. 
Close the issue until we are getting any additional details?

**Comment by Nekromancer** [comment]
Yes, nothing we can do more until i get the device

**Comment by Nekromancer** [comment]
I wasn't able to get the device itself, but i confirmed that this application was sideloaded from another device. APK on that another device was dynamically created from AppBundle. No native libraries were found, since that was missmatch in architecture between devices. Problem with AboutLibraries was only one of maaaany others, so i guess this bug occurence is nothing but anomaly :)

**Comment by mikepenz** [comment]
Thank you so much for reporting back. that's actually quite interesting :D
