### ISSUE TITLE
IllegalStateException: Please provide the data via the provided APIs

### ISSUE THREAD

**Issue by AlinaPohl** [mikepenz/AboutLibraries#707]
## About this issue

Hey, I wrote an android module in compose, which implements this very cool library. In there I just call the LibrariesContainer like:

```kotlin
Scaffold {
                    LibrariesContainer(modifier = Modifier.padding(horizontal = 16.dp))
                }
```

Everything works fine until I export my library and import it into another project. Then I get this error:

```
java.lang.IllegalStateException: Please provide the data via the provided APIs
        at com.mikepenz.aboutlibraries.Libs.<init>(Libs.kt:35)
        at com.mikepenz.aboutlibraries.Libs$Builder.build(Libs.kt:60)
        at com.mikepenz.aboutlibraries.ui.compose.LibrariesKt$LibrariesContainer$1.invokeSuspend(Libraries.kt:41)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:68)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1075)
        at android.view.Choreographer.doCallbacks(Choreographer.java:897)
        at android.view.Choreographer.doFrame(Choreographer.java:822)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1062)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:7892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

For the Export/Import a maven artifact is built and zipped and the zip goes in root/libs/name-of-lib/name-of-lib.zip. In the build.gradle the lib is unzipped and implemented afterwards.

## Details
- Used library version: 10.0.0-b05
- Used gradle build tools version: 7.0.3
- Android Studio version: Arctic Fox | 2020.3.1 Patch 4

Any help is appreciated.

**Comment by mikepenz** [comment]
The `compose` module for `Android` targets uses the `context` from Android to trigger the retrieval of the generated data by the plugin: 

https://github.com/mikepenz/AboutLibraries/blob/develop/aboutlibraries-compose/src/androidMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/Libraries.kt#L46-L49

`withContext(context)`

This is implemented in the `core` module for `Android` targets like: https://github.com/mikepenz/AboutLibraries/blob/develop/aboutlibraries-core/src/androidMain/kotlin/com/mikepenz/aboutlibraries/util/AndroidExtensions.kt#L23-L25

It seems that no data was loaded in this step. can you see if you see output like `Could not retrieve libraries`? 

Does the target project include a raw resource file `aboutlibraries`?

**Comment by AlinaPohl** [comment]
> It seems that no data was loaded in this step. can you see if you see output like Could not retrieve libraries?

Ah yes, I got this in the log.

> Does the target project include a raw resource file aboutlibraries?

No it doesn't.

**Comment by mikepenz** [comment]
@AlinaPohl that's the problem. 

The `AboutLibraries` library uses the `aboutlibraries` raw resource file generated by the plugin to display the included libraries. 

Could you maybe explain more on your usecase? Which dependencies do you want to display in this case? 
Is there a reason for not having the `aboutlibraries` raw resource file generated by the plugin?

**Comment by AlinaPohl** [comment]
Whoops, yeah right. I just totally forgot to generate this file 🤦‍♀️ It's working now, thanks a lot 👍 
In general I need to display all dependencies used from the host app and of course also from the module.

**Comment by mikepenz** [comment]
@AlinaPohl if you have the plugin in the host app that should properly resolve all transitive dependencies :) 

Please let me know if there are further questions. 

I'll write myself a note to expand on the error message to hopefully better assist.
