### ISSUE TITLE
invocation of 'Task.project' at execution time is unsupported. (Breaks configuration cache)

### ISSUE THREAD

**Issue by zoltish** [mikepenz/AboutLibraries#764]
## About this issue

I run into this every once in a while; Id estimate 1-3 times during 10-15 hours of coding. Building the project again works.

Im using a couple of gradle properties, Ill include them below.
```
#Kotlin
kotlin.code.style=official
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false
android.enableR8.fullMode=true
android.defaults.buildfeatures.buildconfig=false
#Gradle
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.configureondemand=true
org.gradle.unsafe.configuration-cache=true
org.gradle.jvmargs=-Xmx16g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC
```
## Stack trace

```
Task `:feature:legal:collectDependencies` of type `com.mikepenz.aboutlibraries.plugin.AboutLibrariesCollectorTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.5-rc-1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

Caused by: org.gradle.api.InvalidUserCodeException: Invocation of 'Task.project' by task ':feature:legal:collectDependencies' at execution time is unsupported.
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onTaskExecutionAccessProblem(ConfigurationCacheProblemsListener.kt:96)
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onProjectAccess(ConfigurationCacheProblemsListener.kt:59)
	at org.gradle.api.DefaultTask.getProject(DefaultTask.java:59)
        ....
	at com.mikepenz.aboutlibraries.plugin.AboutLibrariesCollectorTask.action(AboutLibrariesCollectorTask.kt:30) <--
```

## Details

- [x] Used library version: 10.3.0
- [x] Used gradle build tools version: 7.4.0-alpha04
- [x] Used tooling / Android Studio version: #AI-221.3427.89.2211.8689873

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by zoltish** [comment]
I may have jinxed it.

Since sharing this, my builds fail roughly 30% of the time due to this. Its still faster than skipping configurationCache altogether though, just a bit frustrating!

**Comment by mikepenz** [comment]
@zoltish yeah it definitely has been inconsistent for me too. Any help regarding configuration cache would be highly appreciated. 

----

An alternative solution to faster build times:
- disable the registration of the Android related tasks
- manually execute the creation during CI build time 
- include the generated libs as part of your SCM (you will see what changes over time) 
- save on build times / generation times for your team

**Comment by mikepenz** [comment]
Can you please retry with `10.4.0-b01`

**Comment by mikepenz** [comment]
@zoltish you are welcome. Thanks! 

Can't promise v10.4.0-b01 is solving it a 100% but it looked to be ok in local tests, otherwise a demo app will surely help to investigate further. 

No worries. It will stay a beta for a bit anyways I think, depending then `compose-jb` `1.2.0` will be shipped

**Comment by zoltish** [comment]
@mikepenz Im unable to depend on 10.4.0-b01 for some reason. Is it published differently to the earlier releases by any chance?

```
A problem occurred configuring root project 'ProgressionFlow'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin:10.4.0-b01.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/mikepenz/aboutlibraries/plugin/aboutlibraries-plugin/10.4.0-b01/aboutlibraries-plugin-10.4.0-b01.pom
       - https://dl.google.com/dl/android/maven2/com/mikepenz/aboutlibraries/plugin/aboutlibraries-plugin/10.4.0-b01/aboutlibraries-plugin-10.4.0-b01.pom
       - https://plugins.gradle.org/m2/com/mikepenz/aboutlibraries/plugin/aboutlibraries-plugin/10.4.0-b01/aboutlibraries-plugin-10.4.0-b01.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html


```

**Comment by mikepenz** [comment]
hmmm should be here as usual: https://plugins.gradle.org/plugin/com.mikepenz.aboutlibraries.plugin 🤔

**Comment by zoltish** [comment]
@mikepenz Just thought Id let you know that Ive had 0 issues since upgrading. Thank you :)

**Comment by mikepenz** [comment]
@zoltish thank you so much, that's great to hear
