### ISSUE TITLE
withLibs results in crash

### ISSUE THREAD

**Issue by DevMarkz** [mikepenz/AboutLibraries#777]
## About this issue

- Briefly describe the issue
  withLibs results in crash

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.mikepenz.aboutlibraries.LibsBuilder)
        at android.os.Parcel.writeSerializable(Parcel.java:2177)
        at android.os.Parcel.writeValue(Parcel.java:1943)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:1035)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
        at android.os.Bundle.writeToParcel(Bundle.java:1304)
        at android.os.Parcel.writeBundle(Parcel.java:1104)
        at android.content.Intent.writeToParcel(Intent.java:11764)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2867)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1743)
        at android.app.Activity.startActivityForResult(Activity.java:5465)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
        at android.app.Activity.startActivityForResult(Activity.java:5423)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
        at android.app.Activity.startActivity(Activity.java:5809)
        at android.app.Activity.startActivity(Activity.java:5762)
        at com.mikepenz.aboutlibraries.LibsBuilder.start(LibsBuilder.kt:391)
        at com.mikepenz.aboutlibraries.LibsBuilder.activity(LibsBuilder.kt:398)
```
        
- How can the issue be reproduced / sample code

```
            val localLib = Libs.Builder().withJson(requireActivity(), R.raw.aboutlibraries).build()
            LibsBuilder().withLibs(localLib)
                .activity(requireContext())
```

## Details
- [ ] Used library version
   10.3.1
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ Y ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ Y ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ Y ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ Y ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ Y ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Without having a closer look, I suppose that there may have been too much data in the `LibsBuilder` class.

**Comment by DevMarkz** [comment]
The json contains indeed a lot a data (170kb) but even if I remove all licenses and keep just 1 library (just 4 kb remaining) I still get the same error

**Comment by mikepenz** [comment]
It could be something else too, it was only the first thought based on the trace. will need to dig deeper in it possibly.

**Comment by mikepenz** [comment]
Oh wow, not sure how it worked when I first tested, but the problem is that the classes from `Kotlin Multiplatform` are not serializeable, which is a problem. 

Going to adjust this for the legacy UI module in the upcoming release.
