### ISSUE TITLE
IllegalStateException during OnSaveInstanceState

### ISSUE THREAD

**Issue by danielbanks** [mikepenz/AboutLibraries#797]
## About this issue

We are observing an IllegalStateException when OnSaveInstanceState is called. 
Library version 10.4.0

**Stacktrace**
```
Fatal Exception: java.lang.IllegalStateException: Check failed.
       at androidx.compose.runtime.saveable.SaveableStateRegistryImpl.performSave(SaveableStateRegistry.kt:138)
       at androidx.compose.ui.platform.DisposableSaveableStateRegistry_androidKt$DisposableSaveableStateRegistry$registered$1.saveState(DisposableSaveableStateRegistry.android.kt:83)
       at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.java:247)
       at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
       at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:368)
       at android.app.Activity.performSaveInstanceState(Activity.java:2208)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1488)
       at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6095)
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5432)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5361)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5471)
       at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:247)
       at android.app.ActivityThread.main(ActivityThread.java:8676)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Implementation**:

```
class ViewLicensesActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyTheme {
                Scaffold(
                    topBar = {
                        MyTopAppBar(
                            titleId = R.string.open_source_licenses_title,
                        )
                    },
                ) {
                    LibrariesContainer(
                        modifier = Modifier.fillMaxSize()
                    )
                }
            }
        }
    }
}
```

**Steps to reproduce**:

1. Turn on don't keep activities
2. Navigate to license activity
3. Click on an item
4. Background the app
5. Foreground the app

## Details
[10.4.0] Used library version
[7.2.2] Used gradle build tools version
[1.7.10] Kotlin version
[1.2.1] Compose version
[1.3.0] Compose compiler version
[Chipmunk Patch 2] Android Studio version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [X] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@danielbanks would you please be so kind to add the stacktrace.

**Comment by danielbanks** [comment]
@mikepenz edited to include stacktrace :)

**Comment by danielbanks** [comment]
OK thanks for the fix @mikepenz
