### ISSUE TITLE
Crash when using supportLibrary 22.1.0

### ISSUE THREAD

**Issue by wintersandroid** [mikepenz/AboutLibraries#81]
Updated my app to support library 22.1.0 and now opening the activity crashes.

Callstack
```
  java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.mikepenz.aboutlibraries.Libs$Builder)
            at android.os.Parcel.writeSerializable(Parcel.java:1394)
            at android.os.Parcel.writeValue(Parcel.java:1341)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
            at android.os.Bundle.writeToParcel(Bundle.java:1034)
            at android.os.Parcel.writeBundle(Parcel.java:669)
            at android.content.Intent.writeToParcel(Intent.java:7485)
            at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2411)
            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
            at android.app.Activity.startActivityForResult(Activity.java:3745)
            at android.app.Activity.startActivityForResult(Activity.java:3706)
            at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
            at android.app.Activity.startActivity(Activity.java:4016)
            at android.app.Activity.startActivity(Activity.java:3984)
            at com.mikepenz.aboutlibraries.Libs$Builder.start(Libs.java:960)
            at nz.org.winters.android.widgetscommon.activities.PopupBaseActivity.createAboutActivity(PopupBaseActivity.java:612)
            at nz.org.winters.android.widgetscommon.activities.PopupBaseActivity.doAbout(PopupBaseActivity.java:585)
            at nz.org.winters.android.widgetscommon.activities.PopupBaseActivity$2.itemClicked(PopupBaseActivity.java:289)
            at nz.org.winters.android.widgetscommon.views.DrawLayout.onClickAbout(DrawLayout.java:250)
            at nz.org.winters.android.widgetscommon.views.DrawLayout_$1.onClick(DrawLayout_.java:104)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.io.NotSerializableException: com.mikepenz.aboutlibraries.util.Colors
            at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
            at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
            at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
            at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
            at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
            at android.os.Parcel.writeSerializable(Parcel.java:1389)
            at android.os.Parcel.writeValue(Parcel.java:1341)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
            at android.os.Bundle.writeToParcel(Bundle.java:1034)
            at android.os.Parcel.writeBundle(Parcel.java:669)
            at android.content.Intent.writeToParcel(Intent.java:7485)
            at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2411)
            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
            at android.app.Activity.startActivityForResult(Activity.java:3745)
            at android.app.Activity.startActivityForResult(Activity.java:3706)
            at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
            at android.app.Activity.startActivity(Activity.java:4016)
            at android.app.Activity.startActivity(Activity.java:3984)
            at com.mikepenz.aboutlibraries.Libs$Builder.start(Libs.java:960)
            at nz.org.winters.android.widgetscommon.activities.PopupBaseActivity.createAboutActivity(PopupBaseActivity.java:612)
            at nz.org.winters.android.widgetscommon.activities.PopupBaseActivity.doAbout(PopupBaseActivity.java:585)
            at nz.org.winters.android.widgetscommon.activities.PopupBaseActivity$2.itemClicked(PopupBaseActivity.java:289)
            at nz.org.winters.android.widgetscommon.views.DrawLayout.onClickAbout(DrawLayout.java:250)
            at nz.org.winters.android.widgetscommon.views.DrawLayout_$1.onClick(DrawLayout_.java:104)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I have the following in gradle.
```
  compile('com.mikepenz.aboutlibraries:library:4.6.0@aar') {
        transitive = true
        exclude group: 'com.android.support', module: 'support-v4'
    }
```

And launch, with cusom libraries specified in xml files.
```
 private void createAboutActivity() {

    Colors colors = new Colors(
        getResources().getColor(R.color.material_primary),
        getResources().getColor(R.color.material_primary)
    );

    Libs.Builder builder = new Libs.Builder()
        .withFields(R.string.class.getFields())
        .withAboutVersionShown(true)
        .withAboutIconShown(true)
        .withActivityColor(colors)
            //.withActivityTheme(R.style.AppTheme)
        .withActivityTitle(getString(R.string.about) + " " + getString(R.string.app_name))
        .withAnimations(true)
        .withAboutDescription(getAboutString())
        .withAutoDetect(true);

// Checkout "ACRA"
    builder.withLibraries("updateChecker","AndroidAnnotations","NineOldAndroids","RetroFit",
        "aboutlibraries" ,"androidBetterpickers","DBFlow",
        "jsoup","stickylistheaders","CircularFloatingActionMenu",
        "floatingacctionbutton","superrecyclerview","recyclerviewstickyheaders",
        "recyclerviewmultiselect","expandablelayout");
    builder.start(this);

  }

```

**Comment by mikepenz** [comment]
@wintersandroid i have to update all the libs for the new support libraries because they have changed many things, please use the previous version for now, until i was able to update.
