### ISSUE TITLE
Black activity and show only app bar

### ISSUE THREAD

**Issue by maxrave-dev** [mikepenz/AboutLibraries#935]
## About this issue

- Black activity and show only app bar
<img src="https://github.com/mikepenz/AboutLibraries/assets/113747128/c35870b3-b844-4a55-ac6a-bc5b9ef2cb42" height=700/><br/>
- This code I use to open activity
```
binding.bt3rdPartyLibraries.setOnClickListener {
    getJsonDataFromAsset(requireContext())?.let {
        LibsBuilder()
            .withLicenseShown(true)
            .withVersionShown(true)
            .withActivityTitle(getString(R.string.third_party_libraries))
            .withSearchEnabled(true)
            .withEdgeToEdge(true)
            .withLibs(
                Libs.Builder()
                    .withJson(it) // provide the metaData (alternative APIs available)
                    .build()
            )
            .start(requireContext())
    }
}
```
- Log cat show this logs:
```
android.view.WindowLeaked: Activity com.mikepenz.aboutlibraries.ui.LibsActivity has leaked window android.widget.LinearLayout{8fc9bfb V.E...... .......D 0,0-143,55} that was originally added here
                                                                	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:943)
                                                                	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:931)
                                                                	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:391)
                                                                	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
                                                                	at com.android.internal.view.TooltipPopup.show(TooltipPopup.java:74)
                                                                	at android.view.View.showTooltip(View.java:31396)
                                                                	at android.view.View.showHoverTooltip(View.java:31430)
                                                                	at android.view.View.$r8$lambda$27VXCdyLVNkujfByQKuywAc_nkI(Unknown Source:0)
                                                                	at android.view.View$$ExternalSyntheticLambda2.run(Unknown Source:2)
                                                                	at android.os.Handler.handleCallback(Handler.java:942)
                                                                	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                	at android.os.Looper.loopOnce(Looper.java:201)
                                                                	at android.os.Looper.loop(Looper.java:288)
                                                                	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                	at java.lang.reflect.Method.invoke(Native Method)
                                                                	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
## Details
- [x] Used library version
- [x] Used support library version
- [x] Used gradle build tools version
- [x] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
When you open the activity, can you verify the libs you load contain information?

**Comment by maxrave-dev** [comment]
![image](https://github.com/mikepenz/AboutLibraries/assets/113747128/35052438-a7f0-4d3f-b670-da973c685987)
This is aboutliraries.json but when load is only {"metadata":{"generated":"2023-11-05T15:48:30.735Z"},"libraries":[] }

**Comment by mikepenz** [comment]
So it seems something is wrong with the loading logic maybe? (either wrong file loaded or so 🤔 )

The json string you get? is it the one you attached above?

**Comment by maxrave-dev** [comment]
I fixed by using this code 
```
val inputStream = requireContext().resources.openRawResource(R.raw.aboutlibraries)
            val scanner = Scanner(inputStream).useDelimiter("\\A")
            val stringBuilder = StringBuilder()
            while (scanner.hasNextLine()) {
                stringBuilder.append(scanner.nextLine())
            }
            Log.w("AboutLibraries", stringBuilder.toString())
            val localLib = Libs.Builder().withJson(stringBuilder.toString()).build()
                val intent = LibsBuilder()
                    .withLicenseShown(true)
                    .withVersionShown(true)
                    .withActivityTitle(getString(R.string.third_party_libraries))
                    .withSearchEnabled(true)
                    .withEdgeToEdge(true)
                    .withLibs(
                        localLib
                    )
                    .intent(requireContext())
                startActivity(intent)
        }
```
